// Code generated by pamgen version (devel). DO NOT EDIT.

package extmocks

import (
	"github.com/golang/mock/gomock"
	"github.com/sirkon/deepequal"
	"reflect"
)

// ReaderMock interface io.Reader mock
type ReaderMock struct {
	ctrl     *gomock.Controller
	recorder *ReaderMockRecorder
}

// ReaderMockRecorder records expected calls of io.Reader
type ReaderMockRecorder struct {
	mock *ReaderMock
}

// NewReaderMock creates ReaderMock instance
func NewReaderMock(ctrl *gomock.Controller) *ReaderMock {
	mock := &ReaderMock{
		ctrl: ctrl,
	}
	mock.recorder = &ReaderMockRecorder{mock: mock}
	return mock
}

// EXPECT returns expected calls recorder
func (m *ReaderMock) EXPECT() *ReaderMockRecorder {
	return m.recorder
}

// Read method to implement io.Reader
func (m *ReaderMock) Read(p []byte) (n int, err error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", p)
	n, _ = ret[0].(int)
	err, _ = ret[1].(error)
	return n, err
}

// Read register expected call of method io.Reader.Read
func (mr *ReaderMockRecorder) Read(p interface{}) *gomock.Call {
	if p != nil {
		if _, ok := p.(gomock.Matcher); !ok {
			p = deepequal.NewEqMatcher(p)
		}
	}
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*ReaderMock)(nil).Read), p)
}
